---
Name: iqformbuilder
---
SilverStripe\Control\Controller:
  extensions:
    - IQnection\FormBuilder\Control\FormHandler
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.formbuilder:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "formbuilder"
      defaultLifetime: 21600
SilverStripe\Control\Director:
  rules:
    '_form-builder-preview': IQnection\FormBuilder\Control\FormBuilderPreview

 